# TeXシステムインストールの概略

TeXと呼ばれる組版処理システムは、専門性の高い複雑なシステムなので、
使いこなすためには専門的な知識の勉強が必要となります。
しかし、Rと連携して用いられるRmarkdownを使った レポート作成システム
としてTeXを利用する場合には、
TeX自体の専門的な知識はほとんど必要ありません。

また、RmarkdownからのみしかTeXを利用しない人のために開発されている
「tinytex」というTeXを管理するためのRパッケージがあるので、
TeXの管理についてもほとんど知識は必要ありません。

さて、ここでTeXシステムのインストールと言っていますが、
TeX以外でTeXに密接に関連するもののインストールや設定も行います。
ですから、正確には、RでRmarkdownパッケージを使ってpdf出力をするために
必要な設定を行います。そして、これらの設定作業を行うことで、
このRmarkdownを利用して作られているrepocoパッケージも動くようになります。


## 作業の流れ

これから行う設定作業は、
幾つかの作業を行わなければならないので、
何の作業をどういう順序で行うのか整理して理解しやすいように、
まず、具体的な作業の概略を以下に述べておきます。

1. RパッケージtinytexをRにインストール
1. インストールされたtinytexの関数を使って、R上でtexをインストール
1. ghostscriptと呼ばれるプログラムをウィンドウズにインストール
1. ウィンドウズの環境変数pathにインストールされたghostscriptのbinとlibディレクトリを追加する
1. R上でtinytexを使って、texのパッケージをインストールする。

以上で、R上でrmarkdownを使ってpdf出力が出来るようになります。
そして、repocoも動くようになります。


## 注意すべき事項

ここで紹介しているインストール作業は、
全て、インターネット上で公開されているパッケージをインストールして行います。
ですから、作業の最中は、常にインターネットに接続している必要があります。

また、インストールの作業は思った以上の時間がかかる事があります、
コンソールでインストール作業が行われている場合、
プロンプトがすぐに戻ってこなくても、不具合ではありません。
長いときには表示が止まったままで数分掛かることもあることを頭に入れておきましょう。



